# Generated by Django 2.2.6 on 2023-01-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('name', models.CharField(max_length=64, verbose_name='周期任务名称')),
                ('cron', models.CharField(max_length=128, verbose_name='调度策略')),
                ('total_run_count', models.PositiveIntegerField(default=0, verbose_name='执行次数')),
                ('last_run_at', models.DateTimeField(null=True, verbose_name='上次运行时间')),
                ('creator', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('priority', models.IntegerField(default=100, verbose_name='流程优先级')),
                ('queue', models.CharField(default='', max_length=512, verbose_name='流程使用的队列名')),
                ('celery_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.PeriodicTask', verbose_name='celery 周期任务实例')),
            ],
            options={
                'verbose_name': '维护者相关字段',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodicTaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='创建者')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='更新者')),
                ('ex_data', models.TextField(verbose_name='异常信息')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('start_success', models.BooleanField(default=True, verbose_name='是否启动成功')),
                ('priority', models.IntegerField(default=100, verbose_name='流程优先级')),
                ('queue', models.CharField(default='', max_length=512, verbose_name='流程使用的队列名')),
                ('periodic_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instance_rel', to='celery_task.PeriodicTask', verbose_name='周期任务')),
            ],
            options={
                'verbose_name': '维护者相关字段',
                'abstract': False,
            },
        ),
    ]
